config/routes.rb
Wikipages::Application.routes.draw do
  resources :contacts

  root :to => 'contacts#index'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all
  end

  def show
    @contact = Contact.find(params[:id])
  end   

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:notice] = 'Your contact was saved.'
    redirect_to contacts_path
    else
      render :new
    end
  end  

  def edit
    @contact = Contact.find(params[:id])
  end 

  def update
    @contact = Contact.find(params[:id])
    if @contact.update(contact_params)
      flash[:notice] = "Contact was updated"
      redirect_to @contact
    else
      render :edit
    end    
  end  

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    flash[:notice] = "Contact deleted"
    redirect_to contacts_path
  end  

private

  def contact_params
    params.require(:contact).permit(:name, :phone, :email)
  end  
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_form.html.erb
<% if @contact.errors.any? %>
  <h3>Please correct these problems:</h3>
    <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

<%= form_for @contact do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :phone %>
  <%= f.text_field :phone %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.submit %>
<% end %>  

app/views/contacts/edit.html.erb
<h1>Edit <%= @contact.name %></h1>

<%= render 'form' %>

app/views/contacts/index.html.erb
<h1>Contacts</h1>

<ul>
  <% @contacts.each do |contact| %>
    <li><%= link_to contact.name, contact %></li>
  <% end %>
 </ul> 

 <p><%= link_to 'New contact', new_contact_path %></p>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

app/views/contacts/show.html.erb
<h1><%= @contact.name %></h1>

<p> Phone: <%= @contact.phone %></p>
<p> Email: <%= @contact.email %></p>

<p><%= link_to 'Edit this contact', edit_contact_path(@contact) %> </p>
<p><%= link_to 'Delete this contact',
                @contact,
                :method => :delete,
                :data => { :confirm => 'Are you sure broda?' } %></p>
<p><%= link_to 'Return to contact listing', contacts_path %> </p>

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
<head>
  <title>Wikipages</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <% if flash[:notice] %>
      <div class="alert alert=info">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert=danger">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>